# Generated by Django 3.1.7 on 2021-04-01 01:47

from django.db import migrations

def populate_db(appreg, ed):
    


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210329_2213'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
